name: CD Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

concurrency:
  group: main
  cancel-in-progress: true

jobs:
  quality-assurance:
    name: Quality Assurance
    uses: ./.github/workflows/pr.yml

  deploy:
    name: Deploy to AWS S3
    needs: quality-assurance
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1

      - name: Install dependencies
        run: npm ci
    
      - name: Build the project
        env:
          VITE_TXT_SINK_API_URL: ${{ secrets.BASE_URL }}
        run: |
          echo "VITE_TXT_SINK_API_URL=${{ secrets.BASE_URL }}" > .env.production
          npm run build

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "dist/"
